<?php
/**
 * Noite Assombrada countdown.
 */
?>
<div class="halloween-countdown-wrapper"
     data-bind="scope: 'halloweenCountdown'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "halloweenCountdown": {
                    "component": "js/countdown",
                    "endDate": "2026-10-31T23:59:59-03:00"
                }
            }
        }
    }
}
</script>